### ISSUE TITLE
Can't load module

### ISSUE THREAD

**Issue by morenoh149** [MattMcFarland/react-darkroom#2]
Hello I'm trying to load the module into my project. I have

``` js
import React from 'react';
import { Darkroom, Canvas } from 'react-darkroom';

export default class ImageModal extends React.Component {

  render() {

    console.log('modal', Canvas);
    console.log('modal', Darkroom);

    return (
      <div className={style.container}>
          <div className={style.imgContainer}>
            <Darkroom>
              <Canvas source={this.props.link} />
            </Darkroom>
          </div>
        </Dialog>
      </div>
    )
  }
}
```

but I get errors

```
modal undefined
warning.js?8a56:45 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ImageModal`.
```

I'm definitely installed the module via npm install.

**Comment by 5um1th** [comment]
So this is what I'm trying to do:

```
import React from 'react';
import { Darkroom, Canvas, History, Toolbar, FilePicker, CropMenu } from 'react-darkroom';
import { Component } from 'react';

export default class App extends Component {
  render() {
    return (
          <div>
            <Darkroom>
              <Canvas source={this.props.link} />
            </Darkroom>
          </div>
    );
  }
}
```

I use the bleeding preset on Babel

and this is the error I see:

I see the Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by MattMcFarland** [comment]
Ah, I wish I had time over the weekend :(  This looks like the babel
preset.

What happens if you remove everything but Darkroom and Canvas from the
import at line 2?  It might be worth taking one thing out at a time as well
until it works again, and for sanity purposes remove all of darkroom to see
what happens.

On Sun, Mar 20, 2016 at 8:50 PM, Sumith Jitta notifications@github.com
wrote:

> So this is what I'm trying to do:
> 
> import React from 'react';
> import { Darkroom, Canvas, History, Toolbar, FilePicker, CropMenu } from 'react-darkroom';
> import { Component } from 'react';
> 
> export default class App extends Component {
>   render() {
>     return (
>           <div>
>             <Darkroom>
>               <Canvas source={this.props.link} />
>             </Darkroom>
>           </div>
>     );
>   }
> }
> 
> I use the bleeding preset on Babel
> 
> and this is the error I see:
> 
> I see the Uncaught Invariant Violation: Element type is invalid: expected
> a string (for built-in components) or a class/function (for composite
> components) but got: undefined.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MattMcFarland/react-darkroom/issues/2#issuecomment-199072188

## 

Matt McFarland

Software Engineer | @docodemore https://twitter.com/docodemore | LinkedIn
http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by morenoh149** [comment]
@MattMcFarland btw my example only attempted to load `Darkroom` and `Canvas`

**Comment by MattMcFarland** [comment]
I'm just now starting to look into the issue again, ran out of time today
but will keep plugging away this week.  Thanks for the patience :)

On Mon, Mar 21, 2016 at 11:02 AM, Harry Moreno notifications@github.com
wrote:

> @MattMcFarland https://github.com/MattMcFarland btw my example only
> attempted to load Darkroom and Canvas
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/MattMcFarland/react-darkroom/issues/2#issuecomment-199328028

## 

Matt McFarland

Software Engineer | @docodemore https://twitter.com/docodemore | LinkedIn
http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by 5um1th** [comment]
FYI I've tried the same with Just Darkroom and Canvas

**Comment by MattMcFarland** [comment]
@morenoh149 and @5um1th - I have just released v0.2.0 which fixes the issue and adds compatibility support.  Please give it a try - you can also see the example running here: https://react-darkroom-example-mattmcfarland.c9users.io/public/

You can see the example use in a live IDE here: https://ide.c9.io/mattmcfarland/react-darkroom-example

**Comment by 5um1th** [comment]
Thanks @MattMcFarland I'll give it a whirl and let you know!

**Comment by 5um1th** [comment]
@MattMcFarland works like a charm!

**Comment by MattMcFarland** [comment]
@5um1th Thanks!
