### ISSUE TITLE
Cannot read property 'cropImage' of undefined

### ISSUE THREAD

**Issue by babylon05** [MattMcFarland/react-darkroom#3]
Hi i'm getting this error:

KitchenSink.js:177 Uncaught TypeError: Cannot read property 'cropImage' of undefined

when I try and confirm a crop on the React Darkroom Kitchen Sink demo running from:
http://localhost:8080/webpack-dev-server/

I wanted to try:
https://react-darkroom-example-mattmcfarland.c9users.io/public/
to see if it was only me but it's not up. 

Thanks!

**Comment by MattMcFarland** [comment]
Hey, I've got it up and running again if you want to take a look.  Let me know if that helps.

Thanks,
Matt

**Comment by babylon05** [comment]
Hey, Narrowing it down, when I clone the git and install this is what I get:

ERROR in The node API for `babel` has been moved to `babel-core`.
 @ multi main

So I uninstall babel  and install babel-loader 
and everything works fine except for the crop confirm that gives me the same error.
KitchenSink.js:177 Uncaught TypeError: Cannot read property 'cropImage' of undefined

Any ideas?

Thanks,
James

**Comment by MattMcFarland** [comment]
I finally found some time to work on this again and fixed this issue... thanks!
