### ISSUE TITLE
Live demo is not working

### ISSUE THREAD

**Issue by mplis-jetsetter** [MattMcFarland/react-darkroom#4]
[This](https://react-darkroom-example-mattmcfarland.c9users.io/public/) page displays an error saying "No application seems to be running here!"

**Comment by JMacLulich** [comment]
Can 2nd this, live demo is not working.

**Comment by MattMcFarland** [comment]
Thanks guys, I'm working on an update and also using something like CI

**Comment by MattMcFarland** [comment]
Fixed...
http://blog.mmcfarland.net/react-darkroom/

**Comment by JMacLulich** [comment]
Thanks @MattMcFarland very nice! I'm looking to incorporate this into a project I'm working on.
