### ISSUE TITLE
Cannot find compiled style sheet on build

### ISSUE THREAD

**Issue by oliverasistemas** [MattMcFarland/react-darkroom#9]
May be I am missing something obvious here, but I am not sure how to import the component css styles. I am importing the KitchenSink boilerplate, like:

import KitchenSink from 'react-darkroom/lib/containers/KitchenSink';

and then: 

render() {
return <div>
                    <KitchenSink />
                </div>
}

**Comment by jakeorr** [comment]
I'm also having trouble with this. The `/src` directory isn't included in the installed package and I can't find darkroom.css elsewhere in the package.
